language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pablomdz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pablomdz/docker-react  npm run test
